; Listing generated by Microsoft (R) Optimizing Compiler Version 19.43.34808.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__D43F3135_concurrencysal@h DB 01H
__809F1F3D_sal@h DB 01H
__F4CF5225_vadefs@h DB 01H
__EFD15DDC_vcruntime@h DB 01H
__0B0C18C1_xkeycheck@h DB 01H
__4B5143EF_yvals_core@h DB 01H
__1B0272D9_corecrt@h DB 01H
__B9985323_float@h DB 01H
__1EECE41E_cfloat DB 01H
__32B4127C_limits@h DB 01H
__FE7CC424_climits DB 01H
__FA660213_vcruntime_new@h DB 01H
__1C1A517F_vcruntime_new_debug@h DB 01H
__935DC21B_crtdbg@h DB 01H
__525804FF_crtdefs@h DB 01H
__31900103_use_ansi@h DB 01H
__CCD35069_yvals@h DB 01H
__BB16330F_corecrt_math@h DB 01H
__3BF2A406_math@h DB 01H
__45DED006_corecrt_malloc@h DB 01H
__13F5961F_stddef@h DB 01H
__FD6DBD68_corecrt_search@h DB 01H
__E2E33A61_corecrt_wstdlib@h DB 01H
__6E5ACABA_stdlib@h DB 01H
__7A93E6D6_cstdlib DB 01H
__CA9E334A_xtr1common DB 01H
__98FE829A_intrin0@inl@h DB 01H
__4B75BDF4_intrin0@h DB 01H
__E225118A_cmath DB 01H
__44420885_corecrt_stdio_config@h DB 01H
__AB601D8D_corecrt_wstdio@h DB 01H
__C1EC35D3_stdio@h DB 01H
__6DA82F99_cstdio DB 01H
__61CC25A1_errno@h DB 01H
__34137F69_vcruntime_string@h DB 01H
__E4C945B4_corecrt_memcpy_s@h DB 01H
__8EAFF484_corecrt_memory@h DB 01H
__6490AEC5_corecrt_wstring@h DB 01H
__E8295E1E_string@h DB 01H
__36014E36_cstring DB 01H
__EF1F6BBA_corecrt_wconio@h DB 01H
__74484FB3_corecrt_wctype@h DB 01H
__3D1D430C_corecrt_wdirect@h DB 01H
__8ECB7138_corecrt_share@h DB 01H
__DB7FEBA6_corecrt_wio@h DB 01H
__9A9F0068_corecrt_wprocess@h DB 01H
__369A9BC3_corecrt_wtime@h DB 01H
__CE789B9D_types@h DB 01H
__9901C817_stat@h DB 01H
__3FCAD62E_wchar@h DB 01H
__F723F9CA_cwchar DB 01H
__B4E37CFC_iosfwd DB 01H
__DF583C7B_cstddef DB 01H
__CEF94706_initializer_list DB 01H
__8CC23C43_stdint@h DB 01H
__C7CD07AB_cstdint DB 01H
__45A5DE0A_type_traits DB 01H
__4D9E635D_utility DB 01H
__F5E92B30___msvc_iter_core@hpp DB 01H
__E01A44BE_xutility DB 01H
__F1B6F3FE_iterator DB 01H
__F7972D0B_share@h DB 01H
__BF896257___msvc_system_error_abi@hpp DB 01H
__F0895B62_cerrno DB 01H
__FA77ED4C_malloc@h DB 01H
__89766DA4_corecrt_terminate@h DB 01H
__DD2B0C13_eh@h DB 01H
__14F4542D_vcruntime_exception@h DB 01H
__9A076A69_exception DB 01H
__1FF70EC4___msvc_sanitizer_annotate_container@hpp DB 01H
__A84FD9E6___msvc_string_view@hpp DB 01H
__780AA97A_limits DB 01H
__8D3CA2FB_new DB 01H
__900BE6BF_xatomic@h DB 01H
__270B009E_xmemory DB 01H
__53D88602_xstring DB 01H
__13495034_stdexcept DB 01H
__08C99DBF_xcall_once@h DB 01H
__64464566_xerrc@h DB 01H
__09416E1F___msvc_threads_core@hpp DB 01H
__0A9237D2_time@h DB 01H
__24968D82_ctime DB 01H
__56DEA7FF_xtimec@h DB 01H
__50DE36B0_xthreads@h DB 01H
__133FF5B8_atomic DB 01H
__B7948F9F_system_error DB 01H
__E107CDAF_vcruntime_typeinfo@h DB 01H
__90C5B7A7_typeinfo DB 01H
__C4A4A5F4_memory DB 01H
__E8E1F2FB_xfacet DB 01H
__7045DB1A___msvc_xlocinfo_types@hpp DB 01H
__1EC467ED_ctype@h DB 01H
__6263C83E_cctype DB 01H
__791C33B7_locale@h DB 01H
__E93F3A07_clocale DB 01H
__8F4C546F_xlocinfo DB 01H
__8CE6F233_xlocale DB 01H
__B6A9237C_xiosbase DB 01H
__11E9E888_streambuf DB 01H
__12619424_xlocnum DB 01H
__75F198ED_ios DB 01H
__B8A56285___msvc_ostream@hpp DB 01H
__FC261DCD_istream DB 01H
__9FF628F7_ostream DB 01H
__82633EA1_iostream DB 01H
__2E334632_Log@h DB 01H
__4BA480ED_Main@cpp DB 01H
msvcjmc	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	main
PUBLIC	__JustMyCode_Default
PUBLIC	??_C@_05COLMCDPH@Hello@				; `string'
PUBLIC	??_C@_0N@EKHNDJNO@Ptr?5is?5Hello@		; `string'
PUBLIC	??_C@_0M@GBAJGOJG@Ptr?5is?5null@		; `string'
EXTRN	__imp_?get@?$basic_istream@DU?$char_traits@D@std@@@std@@QEAAHXZ:PROC
EXTRN	?Log@@YAXPEBD@Z:PROC				; Log
EXTRN	_RTC_InitBase:PROC
EXTRN	_RTC_Shutdown:PROC
EXTRN	__CheckForDebuggerJustMyCode:PROC
EXTRN	__imp_?cin@std@@3V?$basic_istream@DU?$char_traits@D@std@@@1@A:BYTE
;	COMDAT pdata
pdata	SEGMENT
$pdata$?__empty_global_delete@@YAXPEAX@Z DD imagerel $LN3
	DD	imagerel $LN3+42
	DD	imagerel $unwind$?__empty_global_delete@@YAXPEAX@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?__empty_global_delete@@YAXPEAX_K@Z DD imagerel $LN3
	DD	imagerel $LN3+47
	DD	imagerel $unwind$?__empty_global_delete@@YAXPEAX_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$main DD	imagerel $LN6
	DD	imagerel $LN6+123
	DD	imagerel $unwind$main
pdata	ENDS
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
_RTC_Shutdown.rtc$TMZ DQ FLAT:_RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
_RTC_InitBase.rtc$IMZ DQ FLAT:_RTC_InitBase
rtc$IMZ	ENDS
;	COMDAT ??_C@_0M@GBAJGOJG@Ptr?5is?5null@
CONST	SEGMENT
??_C@_0M@GBAJGOJG@Ptr?5is?5null@ DB 'Ptr is null', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0N@EKHNDJNO@Ptr?5is?5Hello@
CONST	SEGMENT
??_C@_0N@EKHNDJNO@Ptr?5is?5Hello@ DB 'Ptr is Hello', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_05COLMCDPH@Hello@
CONST	SEGMENT
??_C@_05COLMCDPH@Hello@ DB 'Hello', 00H			; `string'
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$main DD	025050f01H
	DD	010a230fH
	DD	070030021H
	DD	05002H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?__empty_global_delete@@YAXPEAX_K@Z DD 025051801H
	DD	01132318H
	DD	0700c001dH
	DD	0500bH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?__empty_global_delete@@YAXPEAX@Z DD 025051301H
	DD	010e2313H
	DD	07007001dH
	DD	05006H
xdata	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT main
_TEXT	SEGMENT
ptr$ = 8
main	PROC						; COMDAT
; File D:\Cpp_projects\Cherno\Hello_World\Main.cpp
; Line 7
$LN6:
	push	rbp
	push	rdi
	sub	rsp, 264				; 00000108H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__4BA480ED_Main@cpp
	call	__CheckForDebuggerJustMyCode
	npad	1
; Line 8
	lea	rax, OFFSET FLAT:??_C@_05COLMCDPH@Hello@
	mov	QWORD PTR ptr$[rbp], rax
; Line 11
	cmp	QWORD PTR ptr$[rbp], 0
	je	SHORT $LN2@main
; Line 12
	mov	rcx, QWORD PTR ptr$[rbp]
	call	?Log@@YAXPEBD@Z				; Log
	npad	1
$LN2@main:
; Line 13
	lea	rax, OFFSET FLAT:??_C@_05COLMCDPH@Hello@
	cmp	QWORD PTR ptr$[rbp], rax
	jne	SHORT $LN3@main
; Line 14
	lea	rcx, OFFSET FLAT:??_C@_0N@EKHNDJNO@Ptr?5is?5Hello@
	call	?Log@@YAXPEBD@Z				; Log
	npad	1
	jmp	SHORT $LN4@main
$LN3@main:
; Line 16
	lea	rcx, OFFSET FLAT:??_C@_0M@GBAJGOJG@Ptr?5is?5null@
	call	?Log@@YAXPEBD@Z				; Log
	npad	1
$LN4@main:
; Line 17
	mov	rcx, QWORD PTR __imp_?cin@std@@3V?$basic_istream@DU?$char_traits@D@std@@@1@A
	call	QWORD PTR __imp_?get@?$basic_istream@DU?$char_traits@D@std@@@std@@QEAAHXZ
	npad	1
; Line 19
	xor	eax, eax
	lea	rsp, QWORD PTR [rbp+232]
	pop	rdi
	pop	rbp
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 224
__formal$ = 232
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File D:\Cpp_projects\Cherno\Hello_World\Main.cpp
; Line 20
$LN3:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 232				; 000000e8H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__4BA480ED_Main@cpp
	call	__CheckForDebuggerJustMyCode
	npad	1
	lea	rsp, QWORD PTR [rbp+200]
	pop	rdi
	pop	rbp
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 224
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File D:\Cpp_projects\Cherno\Hello_World\Main.cpp
; Line 20
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 232				; 000000e8H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__4BA480ED_Main@cpp
	call	__CheckForDebuggerJustMyCode
	npad	1
	lea	rsp, QWORD PTR [rbp+200]
	pop	rdi
	pop	rbp
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
